version: "3"

services:
    elastic-search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        networks:
            - aisuggestu
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
    flume:
        build: flume
        networks: 
            - aisuggestu
    kibana: 
        image: docker.elastic.co/kibana/kibana:7.7.0
        networks: 
            - aisuggestu
        environment: 
            SERVER_NAME: kibana
            ELASTICSEARCH_HOSTS: http://elastic-search:9200
        ports:
            - "5601:5601"
    zoo:
        image: zookeeper:3.4.9
        networks:
            - aisuggestu
        restart: unless-stopped
        hostname: zoo
        ports:
            - "2181:2181"
    kafka:
        image: confluentinc/cp-kafka:5.5.0
        networks:
            - aisuggestu
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zoo:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092, LISTENER_LOCALHOST://localhost:29092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LISTENER_LOCALHOST:PLAINTEXT
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        depends_on:
            - zoo
        ports:
            - "9092:9092"
            - "29092:29092"
    data-ingestion:
        build: dataIngestion
        environment: 
            - GITHUB_TOKEN
        volumes:
            - ./data/:/data/
        entrypoint: [ "/app/execute.sh", "default" ]
    daily-data-ingestion:
        build: dataIngestion
        environment: 
            - GITHUB_TOKEN
        volumes:
            - ./data/:/data/
        entrypoint: [ "/app/execute.sh", "daily" ]
    daily-producer:
        build: dailyProducer
        networks:
            - aisuggestu
        volumes:
            - ./data/:/data/
    daily-consumer:
        build: dailyConsumer
        networks:
            - aisuggestu
    starred-repos-publish:
        build: starredRepoAndPublish
        environment: 
            - GITHUB_TOKEN
        networks:
            - aisuggestu
    spark-consumer-classifier:
        build: spark/MLPipeline_clustering_e_classificazione
        networks: 
            - aisuggestu
        volumes:
            - ./spark/MLPipeline_clustering_e_classificazione:/opt/classificazione_e_clustering
            - ./data/:/opt/classificazione_e_clustering/data/
    spark-implicit-review-classifier:
        build: spark/MLPipeline_tweet_implicit_reviews
        networks: 
            - aisuggestu
        volumes:
            - ./spark/MLPipeline_tweet_implicit_reviews:/opt/classificazione_e_clustering
            - ./data/:/opt/classificazione_e_clustering/data/
    web:
        build: AISuggestU-Web
        network_mode: host
        environment: 
            - GITHUB_TOKEN
        


networks:
    aisuggestu:
        external: false

volumes:
    data-ingestion: 
