version: "3"

services:
    elastic-search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        networks:
            - aisuggestu
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
    publish-to-elastic:
        build: ./publish-to-elastic/docker
        networks:
            - aisuggestu
        stdin_open: true
        tty: true  
        volumes:
            - ./publish-to-elastic/:/shared/
    zoo:
        image: zookeeper:3.4.9
        networks:
            - aisuggestu
        restart: unless-stopped
        hostname: zoo
        ports:
            - "2181:2181"
    kafka:
        image: confluentinc/cp-kafka:5.5.0
        networks:
            - aisuggestu
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zoo:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092, LISTENER_LOCALHOST://localhost:29092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LISTENER_LOCALHOST:PLAINTEXT
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        depends_on:
            - zoo
        ports:
            - "9092:9092"
            - "29092:29092"
    data-ingestion:
        build: dataIngestion
        environment: 
            - GITHUB_TOKEN=TOKEN
        volumes:
            - ./data/:/data/
    daily-producer:
        build: dailyProducer
        networks:
            - aisuggestu
        volumes:
            - ./data/:/data/
    daily-consumer:
        build: dailyConsumer
        networks:
            - aisuggestu
    starred-repos-publish:
        build: starredRepoAndPublish
        environment: 
            - GITHUB_TOKEN=TOKEN
        networks:
            - aisuggestu
    spark-consumer-classifier:
        build: spark
        networks: 
            - aisuggestu
        volumes:
            - ./spark/MLPipeline_clustering_e_classificazione:/opt/classificazione_e_clustering
            - ./data/:/opt/classificazione_e_clustering/data/
    user-recommendation:
        build: user-recommendation
        networks:
            - aisuggestu
    # web:
    #     build: /home/davide/go/src/aisuggestu
    #     networks:
    #         - aisuggestu
    #     ports:
    #         - "8080:8080"
        


networks:
    aisuggestu:
        external: false

volumes:
    data-ingestion: 