version: "3"

services:
    elastic-search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
    publish-to-elastic:
        build: ./publish-to-elastic/docker
        network_mode: host
        stdin_open: true
        tty: true  
        volumes:
            - ./publish-to-elastic/:/shared/
    spark-master:
        image: bde2020/spark-master:2.4.5-hadoop2.7
        container_name: spark-master
        ports:
            - "8080:8080"
            - "7077:7077"
    zoo:
        image: zookeeper:3.4.9
        network_mode: host
        restart: unless-stopped
        #hostname: zoo
        # ports:
        #     - "2181:2181"
    kafka:
        image: confluentinc/cp-kafka:5.5.0
        network_mode: host
        #hostname: kafka
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        depends_on:
            - zoo
        # ports:
        #     - "9092:9092"
    daily-producer:
        build: dailyProducer
        network_mode: host
        #hostname: daily-producer
        stdin_open: true
        tty: true
        volumes:
            - ./dailyProducer/:/shared/
    daily-consumer:
        build: dailyConsumer
        network_mode: host
        stdin_open: true
        tty: true
        volumes:
            - ./dailyConsumer/:/shared/



