version: "2"

services:
    elastic-search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
    spark-master:
        image: bde2020/spark-master:2.4.5-hadoop2.7
        container_name: spark-master
        ports:
            - "8080:8080"
            - "7077:7077"
    zoo:
        image: zookeeper:3.4.9
        restart: unless-stopped
        hostname: zoo
        ports:
            - "2181:2181"
    kafka:
        image: confluentinc/cp-kafka:5.5.0
        hostname: kafka
        ports:
            - "9092:9092"

