version: "2"

services:
    elastic-search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
